### ISSUE TITLE
Cannot save SQL queries

### ISSUE THREAD

**Issue by rgrenonlkr** [brunoenten/pgadmin4-snap#6]
Hello,

I'm using version 8.12 on Ubuntu 24.04.01

I cannot save SQL queries into my home directory

![image](https://github.com/user-attachments/assets/f5ef63cd-c273-435a-baa7-c779f67cdcf7)

1. Is there a fix I can apply by modifying some perm/owner ?
2. What additional information could help you diagnose this issue ?

**Comment by brunoenten** [comment]
Hi @rgrenonlkr, thank you for the bug report. I'm looking into it.

**Comment by brunoenten** [comment]
Please upgrade to the new version (8.12-1), and use this command to enable access to the home directory:

`  snap connect pgadmin4:home`

**Comment by rgrenonlkr** [comment]
Thanks a lot !
